# 启动端口
server:
  port: 8080

# MySQL数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_URL}:3306/${DB_NAME}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      minimumIdle: 20
      maximum-pool-size: 100
      idleTimeout: 300000
      connection-timeout: 400000
      leak-detection-threshold: 400000

mybatis:
  type-aliases-package: cn.nzcer.findgithubdeveloper.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql